# Generated by Django 4.2.14 on 2024-07-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_details',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='booked_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='student',
            name='booked_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.room'),
        ),
    ]
