# Generated by Django 4.2.14 on 2024-07-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_booking_payment_details_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='booked_hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='booked_room',
        ),
    ]
